### ISSUE TITLE
[Bug]: Token Error when selecting an AWS region to register API gateway

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#102]
### Severity

Medium

### What happened?

I'm not familiar enough to know the reason behind the token error. To a user it looks bad. If it is a common error then a more friendly error message would help.

![Screen Shot 2022-07-18 at 5 07 36 PM](https://user-images.githubusercontent.com/138704/179617650-12e7d7bc-2762-460a-ab8c-49827351a59c.png)

**Comment by Abedeen1** [comment]
Hi @SuddenDevelopment ,

Could you please share your AWS Account credentials.

Regards,
Abedeen.

**Comment by muqeetkhan20** [comment]
@SuddenDevelopment yes, this error is due to invalid access key or security token.
@MuqeedA we have to improve the messaging, below are the steps to reproduce this error.
1. Register API Gateway with AWS
2. Supply wrong credentials (access key or security token)
3. OK - It will register AWS gateway.
4. Click on the AWS tile and select the AWS region.
5. You will see the below error.
![image](https://user-images.githubusercontent.com/68276700/180932399-0135df76-7631-4771-aaf5-cc1d4b6e8c3d.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
@Abedeen1 Pls send a proper error message to the UI when we get this error from the Gateway.   Sync up with @MuqeedA for further details.
