### ISSUE TITLE
[Feature]: HMAC Authentication for Supreme Lending

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#13]
### Please describe your problem?

Swagger and authentication details are available here: 
https://app.hubspot.com/contacts/6447911/ticket/802887841/

### How important is this feature?

Very Important

### Describe the solution you'd like?

Support for HMAC is required for authentication. There are no alternatives for this feature. 
The implementation for Supreme Lending is documented in the attached file.

**Comment by intesar** [comment]
@fersy02 remove sensitive data like org names in tickets.

**Comment by fersy02** [comment]
@intesar - Replaced client name and attachments with Hubspot link

**Comment by Mohammed-Luqman-Shareef** [comment]
@fersy02 We dont have hubspot access.  Can you get access for us to look into the ticket.

**Comment by fersy02** [comment]
@Mohammed-Luqman-Shareef emailed all the necessary details as Engineering doesn't have access to Hubspot.

**Comment by AkaramAli** [comment]
@Mohammed-Luqman-Shareef 

As discussed , 
I have gone the steps in the documentation shared by @fersy02  in the email and tried to write a standalone program in Java ,as of now connection is getting timeout while calling the API  due to access issues .
Also this implementation of HMAC Authentication is very specific to one client ,therefore we need to discuss a generic approach to support this kind of feature in APIsec platform .
one approach could be providing an option Pre-request Script similar to postman but we need to further check the feasibility  ..

**Comment by muqeetkhan20** [comment]
@AkaramAli we have tested this in dev and looks good.
Could you please let us know the scanner (in which the script is installed) to test in prod?

**Comment by muqeetkhan20** [comment]
tested in prod, it worked...
