### ISSUE TITLE
[Bug]: New Users unable to login with OKTA SSO

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#156]
### Severity

Blocker

### What happened?

New Users trying to log in with OKTA SSO are redirected to https://cloud.apisec.ai/callback after they click on the APIsec application within Okta.

![image](https://user-images.githubusercontent.com/47815523/190427015-e77b7082-75b2-4a21-a0b0-b9fcc67042e0.png)

**Comment by fersy02** [comment]
The issue is reproducible in-house, and the Engineering team is looking into it.

**Comment by abdul-hai-apisec** [comment]
The issue was introduced with the fix for https://github.com/apisec-inc/Engineering/issues/301 
Workaround: Using system admin privilege manually add the new user to the OKTA enabled org, then they will be able to access APIsec from OKTA.
The fix will be available with the next prod refresh tentatively scheduled for Monday.

**Comment by asifadn9** [comment]
Created custom app of Developer Environment, and invited a user to okta app who is not a user of APIsec,
 The New user has logged into APIsec Dev Env as PM.

![image (2)](https://user-images.githubusercontent.com/87167426/191232641-c502afce-89a9-4bfc-8791-2b80bc764c73.png)
![image](https://user-images.githubusercontent.com/87167426/191232653-af9ca3ec-a49c-4ea6-aab7-4a671cbea232.png)
