### ISSUE TITLE
[Bug]: Postman Workspace Improvements

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#159]
### Severity

Medium

### What happened?

- [x] Onboarded Postman Collections appear with workspace prefix leading to duplicate projects
We onboarded around 80 postman collections from the API Gateway. After introducing the feature to support APIs, we have found that the existing collections onboarded earlier appear with a new name, including Postman Workspace <Workspace Name> as a prefix. This might lead to a duplication of projects as they are not greyed out when they were onboarded earlier.

- [ ] Avoid registering projects with no endpoints
Several APIs exists with no endpoints and hence no playbooks are generated. A proper error message should be displayed upon registering an API with no endpoints

- [ ] APIs fail to register due to payload size
A couple of APIs have failed to register due to the size of the payload. In such cases we shall skip processing ABAC resources

**Comment by fersy02** [comment]
https://github.com/apisec-inc/Support/issues/168

**Comment by AkaramAli** [comment]
1. Postman does not restrict  the collections/APIs with same name in a workspace and across workspaces ,
But in APISec platform it is restricted to have duplicate project names . 
So when Any API/Collection is registered in platform , all other APIs/Collections with the same name is greyed in postman gateway to avoid duplicate project name registrations.

For collections workspace name prefix was added as part of request . #132
For already registered projects there is no backward compatibility as of today , we need to delete and re -register the project.

point 2 ,3  are generic scenarios ,not related to postman gateway - therefore we need to have a generic solution for this which will impact the normal project registration flow  as well .

**Comment by fersy02** [comment]
Backward compatibility is a must. We get continuous improvements, and manually deleting and registering thousands of API projects is a huge task.

**Comment by AkaramAli** [comment]
@fersy02 -
> 1- Onboarded Postman Collections appear with workspace prefix leading to duplicate projects
We onboarded around 80 postman collections from the API Gateway. After introducing the feature to support APIs, we have found that the existing collections onboarded earlier appear with a new name, including Postman Workspace as a prefix. This might lead to a duplication of projects as they are not greyed out when they were onboarded earlier.

A simpler workaround is , to do one time activity to rename any such projects instead of delete/re-register.
As far as  improvements are concerned there should not be any further changes to project name logic (i.e. addition/removal of the prefix workspace in project name).

For both APIs and Collections we will have - `<Workspace name><Space><Project name>`

Can you share the  impacted tenants / projects and its count ,Based on that we can take a call to either manually do this one time or run  onetime backend script/job.

> 2- Avoid registering projects with no endpoints
Several APIs exists with no endpoints and hence no playbooks are generated. A proper error message should be displayed upon registering an API with no endpoints

This is as per design - In the platform it is allowed to register projects without any specs as well as specs with no endpoints. 

> 3- APIs fail to register due to payload size
A couple of APIs have failed to register due to the size of the payload. In such cases we shall skip processing ABAC resources

Yes , we can look into this , provided we can define a criteria for large payload size , could you please share any such Collections/APIs or specs ?

**Comment by AkaramAli** [comment]
@fersy02 , We are yet to receive the requested details so far .
Also its better we close this ticket and create a new ticket in internal board to address issue 3 ..

**Comment by fersy02** [comment]
Please close this ticket, as we haven't faced issues lately. We will open a new ticket if required. Thanks!
