### ISSUE TITLE
[Bug]: API Registration Via Postman collection adds Duplicate Authentications

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#168]
### Severity

Medium

### What happened?

Regression found in the latest development for automatically configuring authentication via Postman collection.
Duplicate entries are added under the Configurations, Environments, and Envs & Creds for User0 through User9 
![image](https://user-images.githubusercontent.com/47815523/193800998-abcac1e9-58cc-4c40-8aa3-9ad50bd8c245.png)

Shared Postman collection with @atef-aa @Mohammed-Luqman-Shareef and @AkaramAli to reproduce the issue.
Steps to reproduce:
1. Register API using Postman collection
2. Review the credentials under Configurations, Environments, and Envs & Creds

Expected Result:
1. Unique Authentication Shall be created with a prefix ROLE_

Actual Result:
1. Duplicate Entries are Generated

**Comment by AkaramAli** [comment]
Credentials are fetched and added in below order..

1. Default 
2. ROLE_USER
3. UserA
4. Post that credentials are added with User{Random(0-9)}.

This collection has 78 credentials (72 token based and 6 Basic)  which is a rare scenario .
Since we are using User{Random(0-9)} random string to add the credentials ,hence the random/duplicate names .
Will look into it to  handle this kind of scenario .

**Comment by muqeetkhan20** [comment]
@AkaramAli  QE have raised similar kind of bug couple of days ago. This looks generic - FYI
https://github.com/apisec-inc/Engineering/issues/371

**Comment by AkaramAli** [comment]
@muqeetkhan20  - Both are different issues and have different steps to reproduce .

**Comment by AkaramAli** [comment]
I am looking into it .

**Comment by AkaramAli** [comment]
Code pushed , Should be available in next prod refresh .

**Comment by YasmeenFatima** [comment]
Working fine, verified in STG env

**Comment by YasmeenFatima** [comment]
Working fine, Verified in prod
