### ISSUE TITLE
[Report]: AI failed to mark /healthy endpoint as FP

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#182]
### Severity

Bug

### What happened?

Both endpoints should be marked as FP.

GET:https://fullnode.devnet.aptoslabs.com/v1/-/healthy
GET:https://fullnode.devnet.aptoslabs.com/v1/spec

**Comment by habeebvulla** [comment]
Issue resolved.

**Comment by habeebvulla** [comment]
Fixed

**Comment by FidaUrRahman** [comment]
verified working..

**Comment by FidaUrRahman** [comment]
@intesar 
It is marking these endpoints as FP when tested through AI-bot API ,

also tried adding these endpoints in netbanking spec via add enpoints functionality , but playbooks of these two endpoints in unsecured category is PASSING , since these are dummy endpoints for netbanking , that's why it is returning 401 , unable to test through UI

can you please verify if it is working fine with UI as well

**Comment by intesar** [comment]
@habeebvulla @FidaUrRahman - thanks for the improvements. Closing the ticket.
