### ISSUE TITLE
[Report]: Log4j Injection category is wrongly grouped into the Compliance categories

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#199]
### Severity

Bug

### What happened?

Steps to reproduce:

1. Log into the API tenant
2. Navigate to a project, Configurations, Categories
3. Select Compliance from the Filter drop-down

Expected Result: 
The Log4j Injection category shouldn't appear in the list.

Actual Result:
The Log4j Injection category appears in the list.

**Comment by shamiulla-apisec** [comment]
@fersy02 This is a backend issue. Data comes from backend.

**Comment by fersy02** [comment]
@shamiulla-apisec, thanks for the update. Marked it as a bug.

**Comment by MuqeedA** [comment]
@Mohammed-Luqman-Shareef & @fersy02 ,

The injection and compliance categories are separated based on the OWASP rank on UI side. If any category is to be considered as an injection category, it should be marked as OWASP-API8.

**Rank of log4j category data on proj categories page:**
<img width="289" alt="image" src="https://user-images.githubusercontent.com/87184027/198965784-e53b22f8-d3d7-4f34-9c42-4941b37347d3.png">

**Rank of Log4j category on security categories page:**

<img width="512" alt="image" src="https://user-images.githubusercontent.com/87184027/198965945-2e7ea597-2039-4d5b-874c-e5e6e9a15ad1.png">

**Logic on UI side:**
 ```
 if (res['tags'].includes('OWASP-API8')) {
               this.injectionCategories.push(res);
          }

if (res['tags'].includes('OWASP-API9') || res['tags'].includes('OWASP-API10')) {
        this.complianceCategories.push(res);
    }
```

Since , the log4j category has OWASP rank 10 , it is shown under the compliance category. Please make changes in the owasp ranking on the security category page according to the above logic. Let me know if any change is required on UI logic.

**Comment by fersy02** [comment]
The OWSAP ranking is not a relevant factor to group them as it is volatile and would change in the future.

**Comment by Mohammed-Luqman-Shareef** [comment]
@MuqeedA We need to check custom type, not the owasp tag.
Compliance will have Custom type as Compliance1 and Compliance2
Injection will have custom type as injection and stored_injection

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef we have already discussed this with @intesar. Here is our conversation for your reference.
![image](https://user-images.githubusercontent.com/68276700/199168867-f6522bbf-7258-41e5-b1b4-be757a408576.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
Yes, it is both.  We are not changing the OWASP tag.
In the drop-down filter for compliance categories log4j was also picked up wrongly.  Changing that logic in the ui code.

**Comment by MaimoonaFatima** [comment]
Verified in stg.

**Comment by intesar** [comment]
@Mohammed-Luqman-Shareef @fersy02 Log4j is more of an OWASP API-10. So we'll keep it that way.

**Comment by Mohammed-Luqman-Shareef** [comment]
@MuqeedA Show all categories of OWASP API -9 and OWASP API -10 under Compliance filter.

**Comment by shahidabdul** [comment]
> @MuqeedA Show all categories of OWASP API -9 and OWASP API -10 under Compliance filter.
Ok, Changes done

**Comment by atef-aa** [comment]
Completed. Should be available in the next prod refresh.

**Comment by MaimoonaFatima** [comment]
Verified in dev.

**Comment by MaimoonaFatima** [comment]
Verified in prod.
